services:
  postgres:
    image: postgres:16
    container_name: ecommerce-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ecommerce
      POSTGRES_PASSWORD: ecommerce123
      POSTGRES_DB: ecommerce
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    image: ecommerce-api
    container_name: ecommerce-api
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      DATABASE_URL: "postgresql://ecommerce:ecommerce123@postgres:5432/ecommerce?schema=public"
      JWT_SECRET: "ecommerce_secret_key_123456"
    depends_on:
      - postgres

volumes:
  postgres_data:
